/**
 * Curated, hand-verified relationship chains (Phase 2, section 15).
 *
 * These are NOT auto-generated by walking the registry's affectedBy/affects
 * graph — each one is checked by hand against the actual formulas in
 * lib/calculations/index.ts so nothing here implies a causal link that isn't
 * real. Two deliberate choices worth noting:
 *
 * - "Occupancy" is not used as a chain node: it only drives revenue for
 *   standard/multi-let/student strategies (calcBaseMonthlyRevenue branches
 *   per strategy — STR uses nightly rate × occupied nights, instalment sale
 *   uses a fixed instalment with no occupancy concept at all). Revenue is
 *   universally the right starting point instead.
 * - Where a step's own two "next" metrics are computed independently from
 *   the same shared input rather than one literally feeding the other (e.g.
 *   DSCR and Cash Flow both come from NOI, but DSCR does not feed Cash Flow;
 *   Cash-on-Cash and Equity IRR both come from Initial Equity, but neither
 *   feeds the other) — those are represented as PARALLEL siblings (a
 *   `string[]` step), not a false sequential link.
 */
import { getMetricDefinition } from "./metricDefinitions";

/**
 * Friendly labels for raw DealInputs/DealMetrics fields referenced as chain
 * nodes that aren't in METRIC_DEFINITIONS (either because they're a raw
 * input, like purchasePrice, or a supporting figure rather than a metric in
 * its own right, like annualDebtService).
 */
const FIELD_LABELS: Record<string, string> = {
  purchasePrice: "Purchase Price",
  marketValue: "Market Value",
  monthlyRent: "Monthly Rent",
  occupancyRate: "Occupancy",
  annualDebtService: "Debt Payments",
};

function humanize(key: string): string {
  return key.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/^./, (c) => c.toUpperCase());
}

/** Resolve any registry metric key or raw field key to a short, human label. */
export function getKeyLabel(key: string): string {
  const def = getMetricDefinition(key);
  if (def) return def.shortName ?? def.name;
  return FIELD_LABELS[key] ?? humanize(key);
}

export interface RelationshipChain {
  title: string;
  caption: string;
  /** A plain key is one sequential step; a string[] is a set of parallel siblings at that position (fed by the same prior step, not feeding each other). */
  steps: (string | string[])[];
}

export const RENTAL_RELATIONSHIP_CHAINS: RelationshipChain[] = [
  {
    title: "Revenue → NOI → Debt Coverage & Cash Flow",
    caption:
      "Gross revenue (driven by rent, occupancy, and other income) flows down to NOI, which shapes both how safely your debt is covered and how much cash flow you keep.",
    steps: ["grossRevenueAnnual", "noiAnnual", ["dscr", "cashflowMonthly"]],
  },
  {
    title: "Loan Amount → LTV → Debt Payments → DSCR",
    caption:
      "The size of your loan drives your leverage (LTV) and your debt payments — together, those determine how comfortably the property covers its debt.",
    steps: ["totalLoanAmount", "ltv", "annualDebtService", "dscr"],
  },
  {
    title: "Purchase Price → Initial Equity → Investor Return",
    caption:
      "What you pay (plus costs) sets your total investment; subtracting your loan gives your initial equity — the base both your annual Cash-on-Cash Return and your full-cycle Equity IRR are measured against.",
    steps: ["purchasePrice", "totalInvestment", "initialEquityInvestment", ["netYieldPreTax", "irr"]],
  },
];

export const FLIP_RELATIONSHIP_CHAINS: RelationshipChain[] = [
  {
    title: "Total Cost → Profit → Return",
    caption:
      "Your all-in cost and eventual sale price determine gross and net profit, which drive ROI — and Annualised ROI adjusts that for how long you held the property.",
    steps: ["totalCost", "grossProfit", "netProfit", "roi", "annualisedROI"],
  },
];

export function getRelationshipChainsForStrategy(strategyId: string): RelationshipChain[] {
  return strategyId === "fix_and_flip" ? FLIP_RELATIONSHIP_CHAINS : RENTAL_RELATIONSHIP_CHAINS;
}
