/**
 * Plain-English copy for the deterministic verdict engine (Phase 4.14).
 *
 * This module computes NOTHING and judges NOTHING — it only turns the
 * engine's own structured VerdictLabel/VerdictReason output (lib/calculations/verdict.ts)
 * into the exact wording the Phase 4.14 brief specified, so the Summary UI
 * and PDF render identical language from one place instead of drifting
 * apart. AI copy (Deal Coach) is separate and lives in dealCoachPrompt.ts —
 * nothing here is fed to or generated by the model.
 */
import { formatMetricValue } from "./format";
import { METRIC_VALUE_FORMAT } from "./metricBreakdowns";
import type { VerdictLabel, VerdictReason, VerdictUnavailableReason } from "../calculations/verdict";

export const VERDICT_LABEL_COPY: Record<VerdictLabel, { title: string; description: string }> = {
  strong: {
    title: "Strong",
    description:
      "The deal clears AssetVerdict's current safety requirements, meets your Required Return, and has no major operating weakness under the assumptions entered.",
  },
  promising: {
    title: "Promising",
    description:
      "The deal has genuine investment merit and no structural safety failure, but one or more important areas are not strong enough for AssetVerdict's highest verdict.",
  },
  promising_if_negotiated: {
    title: "Promising If Negotiated",
    // Phase 4.16: this label is never returned by deriveDealVerdict — the
    // engine behind this exact copy — so this entry exists only for
    // VerdictLabel's Record<> type completeness (VerdictCard/VerdictExplainer
    // reference every label). The label IS reachable, but only as a
    // separate, conditional fact — see NegotiationOpportunity in
    // lib/calculations/negotiation.ts and its copy in
    // lib/education/negotiationCopy.ts (NEGOTIATION_OPPORTUNITY_TITLE /
    // describeNegotiationOpportunity) — never as this deal's actual verdict.
    description:
      "Not produced as an actual verdict by AssetVerdict's verdict engine. See the deal's separate Negotiation Opportunity status for the conditional fact this label describes.",
  },
  high_risk: {
    title: "High Risk",
    description:
      "A structural financial-safety problem exists under the entered base assumptions, such as debt not being fully covered by NOI or the deal requiring more than all of its gross revenue to cover operating costs and debt service.",
  },
  does_not_meet_target: {
    title: "Does Not Meet Target",
    description:
      "The deal does not currently clear your Required Return, but that does not automatically mean the property is financially unsafe.",
  },
};

/**
 * Fix & Flip's own label copy (Phase 4.20) — the rental copy above talks
 * about DSCR/NOI/operating weakness, none of which this strategy's verdict
 * (lib/calculations/flipVerdict.ts) is derived from. Only the four labels
 * Flip can actually return get an entry; "promising_if_negotiated" falls
 * through to the shared rental copy above (unreachable for Flip either way
 * — see the guardrail in dealCoachPrompt.ts).
 */
const FLIP_VERDICT_LABEL_COPY: Partial<Record<VerdictLabel, { title: string; description: string }>> = {
  strong: {
    title: "Strong",
    description:
      "The Base case is profitable before tax and meets your Required Return. A recorded post-renovation valuation includes a lower confidence bound, and the project remains profitable when AssetVerdict reruns the deal at that lower value — under the current assumptions.",
  },
  promising: {
    title: "Promising",
    description:
      "The Base case is profitable and meets your Required Return, but AssetVerdict does not have a recorded post-renovation valuation with a profitable lower confidence bound, so it cannot classify the deal as Strong.",
  },
  high_risk: {
    title: "High Risk",
    description: "The Base case is estimated to break even or lose money before tax.",
  },
  does_not_meet_target: {
    title: "Does Not Meet Target",
    description: "The Base case is profitable before tax, but the estimated Equity IRR is below your Required Return.",
  },
};

/**
 * Strategy-aware label lookup (Phase 4.20) — Fix & Flip gets its own
 * title/description; every other strategy keeps the original shared
 * `VERDICT_LABEL_COPY`, unchanged. Callers (VerdictCard, VerdictExplainer,
 * DealSummaryPDF) should use this instead of indexing `VERDICT_LABEL_COPY`
 * directly whenever a `strategyId` is available.
 */
export function getVerdictLabelCopy(label: VerdictLabel, strategyId?: string): { title: string; description: string } {
  if (strategyId === "fix_and_flip") {
    return FLIP_VERDICT_LABEL_COPY[label] ?? VERDICT_LABEL_COPY[label];
  }
  return VERDICT_LABEL_COPY[label];
}

export const VERDICT_UNAVAILABLE_COPY: Record<VerdictUnavailableReason, { title: string; description: string }> = {
  strategy_model_incomplete: {
    title: "Not yet available for this strategy",
    description:
      "AssetVerdict does not yet model the seller-financing structure deeply enough to issue a reliable overall verdict.",
  },
  insufficient_required_inputs: {
    title: "Not enough evidence yet",
    description:
      "AssetVerdict cannot currently determine either financial safety or your Required Return status for this deal well enough to issue an overall verdict — check that your finance and cashflow inputs are complete.",
  },
  // Fix & Flip only (Phase 4.20).
  flip_model_unavailable: {
    title: "Not enough evidence yet",
    description:
      "AssetVerdict cannot currently calculate this Flip's financial model — check that your Holding Period is a valid positive number of months.",
  },
  flip_return_evidence_unavailable: {
    title: "Not enough evidence yet",
    description:
      "AssetVerdict cannot currently confirm this Flip's Equity IRR, so it cannot determine whether your Required Return is met.",
  },
};

/** Base sentence templates per reason code, before the value/params are interpolated in. */
const REASON_TEMPLATES: Record<string, (r: VerdictReason, currency: string) => string> = {
  dscr_below_1: (r, c) =>
    `Current NOI does not fully cover annual debt service under the entered base assumptions (DSCR ${fmt(r, c)}).`,
  break_even_above_100: (r, c) =>
    `Operating costs and debt service currently exceed gross revenue under the entered base assumptions (Break-Even Ratio ${fmt(r, c)}).`,
  negative_pretax_cashflow: (r, c) => `The property currently produces negative pre-tax cashflow under the entered base assumptions (${fmt(r, c)}).`,
  break_even_high: () =>
    "Most of the property's gross revenue is already required to cover operating costs and debt service, leaving a narrow margin for error.",
  break_even_caution: () => "Operating costs and debt service require a meaningful share of gross revenue, though within AssetVerdict's caution range.",
  dscr_caution: () => "Debt coverage is acceptable but not strong enough for AssetVerdict's highest rating.",
  dscr_unclassified: () => "AssetVerdict cannot fully certify the safety position because debt coverage is unclassified for this deal.",
  break_even_unclassified: () => "AssetVerdict cannot fully certify the safety position because Break-Even Ratio is unclassified for this deal.",
  high_ltv: () =>
    "The deal uses relatively high leverage — debt as a % of purchase price (Purchase LTV) — under AssetVerdict's current reference bands, which increases sensitivity if income weakens or the property is worth less than the price paid.",
  high_oer: () => "Operating expenses consume a high share of gross income under AssetVerdict's current reference band for this strategy.",
  oer_caution: () => "Operating expenses are within AssetVerdict's caution range for this strategy.",
  oer_unclassified: () => "AssetVerdict has no calibrated operating-efficiency benchmark available for this deal.",
  target_met: (r, c) => `The projected Equity IRR meets or exceeds your Required Return under the entered assumptions (${fmt(r, c)} vs. ${r.params?.requiredReturn}% required).`,
  target_missed: (r, c) => `The projected Equity IRR is below your Required Return under the entered assumptions (${fmt(r, c)} vs. ${r.params?.requiredReturn}% required).`,
  target_unknown: () => "AssetVerdict cannot confirm whether your Required Return is met — Equity IRR isn't available for this deal's current structure.",
  npv_supporting: (r, c) => `Equity NPV: ${fmt(r, c)} — supporting context only, does not independently change the target result.`,
  cap_rate_context: () => "The acquisition cap rate is outside AssetVerdict's current reference range for this strategy — informational only, it does not affect the verdict.",
  instalment_sale_model_incomplete: () => "Instalment Sale is currently modelled like a standard rental income stream; the seller-financing structure itself isn't yet captured.",
  strategy_not_verdict_ready: () => "This strategy does not yet have a calibrated overall verdict.",

  // ---- Fix & Flip (Phase 4.20) --------------------------------------------
  flip_model_unavailable: () => "AssetVerdict cannot currently calculate this Flip's financial model — check that your Holding Period is a valid positive number of months.",
  flip_structural_loss: (r, c) => `The Base case is estimated to break even or lose money before tax (Estimated Profit Before Tax ${fmt(r, c)}).`,
  flip_return_evidence_unavailable: () => "AssetVerdict cannot currently confirm this Flip's Equity IRR, so it cannot determine whether your Required Return is met.",
  flip_profitable: (r, c) => `The Base case is estimated to be profitable before tax (Estimated Profit Before Tax ${fmt(r, c)}).`,
  flip_sale_price_buffer_context: (r, c) => `Base Sale-Price Buffer: ${fmt(r, c)} — descriptive only, AssetVerdict has not calibrated an execution-risk threshold for this figure.`,
  no_exit_value_evidence: () => "No numeric property valuation is recorded to test downside resilience, so AssetVerdict cannot classify this deal as Strong.",
  invalid_valuation_evidence: () => "The recorded valuation figures are internally inconsistent, so AssetVerdict cannot use them as downside evidence for Strong.",
  valuation_basis_unknown: () => "The recorded valuation's basis (current condition vs. post-renovation) was not set, so AssetVerdict cannot treat it as post-renovation exit evidence.",
  valuation_current_condition: () => "The recorded valuation reflects the property's current condition, not its post-renovation value, so AssetVerdict cannot use it as post-renovation exit evidence.",
  no_conservative_lower_bound: () => "The recorded valuation includes a point estimate but no lower confidence bound, so AssetVerdict cannot produce a property-specific downside test.",
  conservative_case_not_profitable: (r, c) => `At the recorded post-renovation lower valuation bound, the project is estimated to break even or lose money before tax (${fmt(r, c)}).`,
  conservative_case_profitable: (r, c) => `At the recorded post-renovation lower valuation bound, the project remains profitable before tax (${fmt(r, c)}).`,
  conservative_target_met: (r, c) => `At that recorded lower valuation bound, the project also continues to meet your Required Return (Equity IRR ${fmt(r, c)}).`,
  conservative_target_missed: (r, c) => `At that recorded lower valuation bound, the project falls below your Required Return (Equity IRR ${fmt(r, c)}) — shown for transparency, this does not block Strong on its own.`,
  conservative_target_unknown: () => "AssetVerdict could not confirm whether the Required Return is met at the recorded lower valuation bound.",
};

function fmt(r: VerdictReason, currency: string): string {
  if (r.value === null || r.value === undefined) return "";
  const format = r.metric ? METRIC_VALUE_FORMAT[r.metric] ?? "number" : "number";
  return formatMetricValue(r.value, format, currency);
}

/** Formats one structured VerdictReason into a plain-English sentence — the single source both the Summary UI and the PDF read from. */
export function formatVerdictReason(reason: VerdictReason, currency = "R"): string {
  const template = REASON_TEMPLATES[reason.code];
  if (template) return template(reason, currency);
  return reason.code.replace(/_/g, " ");
}
