import { calcAllMetrics, calc20YearProjection, type DealInputs, type DealMetrics, type YearlyProjection } from "./index";

export interface ScenarioResult {
  metrics: DealMetrics;
  projection: YearlyProjection[];
}

export interface Scenarios {
  bear: ScenarioResult;
  base: ScenarioResult;
  bull: ScenarioResult;
}

interface SensitivityFactors {
  realGrowthFactor: number; // %
  occupationFactor: number; // %
}

function applyVariant(
  inputs: DealInputs,
  factors: SensitivityFactors,
  direction: -1 | 0 | 1
): DealInputs {
  if (direction === 0) return inputs;

  return {
    ...inputs,
    rentalGrowthRate: inputs.rentalGrowthRate + direction * factors.realGrowthFactor,
    capitalGrowthRate: inputs.capitalGrowthRate + direction * factors.realGrowthFactor,
    occupancyRate: Math.max(
      0,
      Math.min(100, inputs.occupancyRate + direction * factors.occupationFactor)
    ),
  };
}

/**
 * Bear/Base/Bull scenarios generated by shifting rental growth, capital growth,
 * and occupancy by +/- realGrowthFactor / occupationFactor.
 */
export function calcScenarios(
  inputs: DealInputs,
  factors: SensitivityFactors
): Scenarios {
  const bearInputs = applyVariant(inputs, factors, -1);
  const bullInputs = applyVariant(inputs, factors, 1);

  return {
    bear: { metrics: calcAllMetrics(bearInputs), projection: calc20YearProjection(bearInputs) },
    base: { metrics: calcAllMetrics(inputs), projection: calc20YearProjection(inputs) },
    bull: { metrics: calcAllMetrics(bullInputs), projection: calc20YearProjection(bullInputs) },
  };
}
